spring:
  application:
    name: GameForum
gameforum:
  mysql:
    driver: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/game_forum?useSSL=false&serverTimezone=UTC"
    user: "root"
    pwd: "0508"
